### ISSUE TITLE
BPMN are not shown in jupyter

### ISSUE THREAD

**Issue by jalaliamin** [datakurre/jupyterlab-bpmn#2]
Hi

I could not visualize BPMN when cloning the repository and running the example. Is there any more requirements except installing jupyterlab-bpmnlbrary via **pip install jupyterlab-bpmn** ?

Best regards
Amin

**Comment by datakurre** [comment]
@jalaliamin Thanks for the report. It seems that I have somehow failed with packaging the latest versions. pip install jupyterlab-bpmn==0.2.1 works, but it does not save SVG versions of the diagrams onto notebook. I'll fix the release once I know what went wrong.

**Comment by jalaliamin** [comment]
Now I tested it with jupyterlab-bpmn==0.2.1 and I can confirm it works fine in that version. 
Thanks for the quick reply and for releasing this wonderful library! Great job! :-)

**Comment by datakurre** [comment]
Found my issue with packaging. Released jupyterlab-bpmn==0.3.1 which should work properly with just pip install and also saves SVG versions of diagrams for better static notebook support. (e.g. for GitHub preview https://github.com/datakurre/jupyterlab-bpmn/blob/main/examples/example.ipynb)
